eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: oracle.jdbc.OracleDriver
    username: {cipher}8972a6d52298ef62950604fb6afedd4b321dc3c1583b42206da144241efd2e22
    password: {cipher}2426d9e1fa91c36e4c37d63cd44c25a198eb6493c0ec485178498606a2ba8ab4

mybatis:
  type-aliases-package: com.example.book.model
  configuration:
    jdbc-type-for-null: null
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
  mapper-locations:
  - mybatis/mappers/*.xml
